version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    env_file:
      - redis.env
    command: /bin/sh -c "redis-server --requirepass $$PASSWORD --include /usr/local/etc/redis/redis.conf"
    labels:
      - 'name=redis'
      - 'mode=standalone'
    volumes:
      - ./.docker/redis/data:/data
      - ./.docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped

  backend:
    image: ghcr.io/lunaiz-corp/2025_kyunggi-club-backend:latest
    ports:
      - 4000:4000
    env_file:
      - backend.env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    restart: unless-stopped
